### ISSUE TITLE
AES Powershell error

### ISSUE THREAD

**Issue by sparta34** [offsecginger/AggressorScripts#2]
when i try the aes powershell script on windows 10 it gives me errors ;At C:\Users\defenderX\Desktop\t.ps1:1 char:13
+ $eeRFi = @' $cFgXEJfi = "mubpjDsibliCRezgfSeQpYhVnbGukvYk" function R ...
+             ~
No characters are allowed after a here-string header but before the end of the line.
At C:\Users\defenderX\Desktop\t.ps1:1 char:5466
+ ... ([IntPtr]) ([Void]))) $vGUyMjVAa.Invoke([IntPtr]::Zero) '@ If ([IntPt ...
+                                                                ~~
Unexpected token 'If' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedCharactersAfterHereStringHeader

**Comment by offsecginger** [comment]
What settings did you have for it?

**Comment by sparta34** [comment]
i use beacon_https\reverse_https in listener

**Comment by offsecginger** [comment]
It looks like you used the x86 payload, is this correct? Did you generate this from Linux or Windows?

**Comment by offsecginger** [comment]
![image](https://user-images.githubusercontent.com/1323154/50618218-02c85c00-0eb7-11e9-984f-ccabafc5dcf7.png)
I was able to generate an AES PowerShell payload on both Kali, and Windows 10, and executed it in Windows 10.

**Comment by sparta34** [comment]
i generate it from kali linux i have tried both x64 and x86 payloads with no success , and i m using cobaltstrike 3.12

**Comment by offsecginger** [comment]
Can you send a sample of your payload output please?

**Comment by sparta34** [comment]
ok

**Comment by sparta34** [comment]
https://www.sendspace.com/file/npla59 
https://www.sendspace.com/file/kbfdno

both x64 and x86 payloads

**Comment by offsecginger** [comment]
So your issue is that for some reason, your output is not including new lines. There is nothing in the Aggressor Script that removes new lines like this, which leaves me to believe there's some kind of configuration issue on your end. Spin up a fresh kali vm and see if you still see this issue.

![image](https://user-images.githubusercontent.com/1323154/50654822-aebf8500-0f53-11e9-9fb0-a139a34ee8cc.png)

A PowerShell script can be one line if semi colons are properly inserted, but I haven't implemented that into these scripts.

**Comment by sparta34** [comment]
ok i will give it another try thanks for your time

**Comment by offsecginger** [comment]
No problem. Thanks for testing it out!
